### ISSUE TITLE
UnicodeSetAttribute not JSON serializable

### ISSUE THREAD

**Issue by ramiah11** [pynamodb/PynamoDB#242] opened 2017-03-15 17:36 UTC
Getting error while trying to model.save with a simple unicodesetattribute. 
Sample error below:
TypeError: set([u's3://bucket/key']) is not JSON serializable

**Comment by jmphilli** [comment] 2017-06-10 15:18
hi! i added a test to see if this was broken. see [here](https://github.com/pynamodb/PynamoDB/pull/300) -- it looks the issue is resolved with the newest version `3.0.1` -- can you try upgrading in a dev environment? Be warned there are breaking changes

**Closed** 2017-06-16 16:10 UTC
