### ISSUE TITLE
UTCDateTimeAttribute.deserialize swaps month and day

### ISSUE THREAD

**Issue by headdab** [pynamodb/PynamoDB#320] opened 2017-08-02 15:09 UTC
pynamodb==1.4.4

```
>>> import datetime as dt
>>> from pynamodb.attributes import UTCDateTimeAttribute

>>> now = dt.datetime.utcnow()
>>> now
datetime.datetime(2017, 8, 2, 15, 2, 6, 652067)

>>> attr = UTCDateTimeAttribute().serialize(now)
>>> attr
'2017-08-02T15:02:06.652067+0000'

>>> UTCDateTimeAttribute().deserialize(attr)
datetime.datetime(2017, 2, 8, 15, 2, 6, 652067, tzinfo=<UTC>)

```
Note that feeding a datetime through de/serialize swaps the month and day.

**Comment by danlindow** [comment] 2017-08-16 08:44
This could be due to how parser.parse() is handling the data. 
https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.parserinfo

You can see the exact operations that are going on here:
https://github.com/pynamodb/PynamoDB/blob/master/pynamodb/attributes.py#L440-L465

I was not able to reproduce by simply running through it manually however:
`>>> import six
>>> import datetime
>>> from dateutil.parser import parse
>>> now = datetime.datetime.utcnow()
>>> now
datetime.datetime(2017, 8, 16, 8, 38, 31, 766840)
>>> from dateutil.tz import tzutc
>>> test = now.replace(tzinfo=tzutc())
>>> test
datetime.datetime(2017, 8, 16, 8, 38, 31, 766840, tzinfo=tzutc())
>>> fmt = test.astimezone(tzutc()).strftime('%Y-%m-%dT%H:%M:%S.%f%z')
>>> fmt = six.u(fmt)
>>> fmt
u'2017-08-16T08:38:31.766840+0000'
>>> test2 = datetime.datetime.strptime(fmt, '%Y-%m-%dT%H:%M:%S.%f%z')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 317, in _strptime
    (bad_directive, format))
ValueError: 'z' is a bad directive in format '%Y-%m-%dT%H:%M:%S.%f%z'
>>> test2 = parse(fmt)
>>> test2
datetime.datetime(2017, 8, 16, 8, 38, 31, 766840, tzinfo=tzutc())
>>>`

I don't believe these functions are typically called directly as you are doing however, PynamoDB may be doing something with the data as it pulls it back from DDB before it passes it into the deserialize method.

**Comment by garrettheel** [comment] 2017-10-13 16:23
This was fixed in 1.5, please upgrade! https://github.com/pynamodb/PynamoDB/pull/110

**Closed by garrettheel** 2017-10-13 16:23 UTC
