### ISSUE TITLE
zappa: Unknown parameter in input "BillingMode"

### ISSUE THREAD

**Issue by trenta3** [pynamodb/PynamoDB#692] opened 2019-09-13 13:50 UTC
I'm trying to create a table using pynamodb but the table creation process fails with the title error. I haven't found other issues with the same error, and I'm using pynamodb in the suggested way in the documentation.

**About the problem**:
I use pynamodb with zappa and I have, in the same folder where `zappa_settings.json` lives, the following files:

`create_tables.py`:
```python
from models import Post

def create_post():
    if not Post.exists():
        Post.create_table(read_capacity_units=1, write_capacity_units=1, wait=True)
        return "Table post created"
    return "Table post already exists"
```

`models.py`:
```python
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute, UTCDateTimeAttribute
from datetime import datetime

class Post(Model):
    """
    A post of a user.
    """
    class Meta:
        table_name = "social-dev-posts-v1"
        region = "us-east-1"

    creator_id = UnicodeAttribute(hash_key=True)
    datetime = UTCDateTimeAttribute(range_key=True, default=datetime.now)
    content = UnicodeAttribute()
```

They are as per documentation, now I can deploy with `zappa deploy dev`, but when I call the code in the create_post function, it gives this error concerning the BillingMode:
```bash
$ zappa invoke dev create_tables.create_post
...
https://dynamodb.us-east-1.amazonaws.com:443 "POST / HTTP/1.1" 400 150

Calling CreateTable with arguments {'TableName': 'social-dev-posts-v1', 'BillingMode': 'PROVISIONED', 'ProvisionedThroughput': {'ReadCapacityUnits': 1, 'WriteCapacityUnits': 1}, 'AttributeDefinitions': [{'AttributeName': 'creator_id', 'AttributeType': 'S'}, {'AttributeName': 'datetime', 'AttributeType': 'S'}], 'KeySchema': [{'AttributeName': 'creator_id', 'KeyType': 'HASH'}, {'AttributeName': 'datetime', 'KeyType': 'RANGE'}]}

Event before-parameter-build.dynamodb.CreateTable: calling handler <function generate_idempotent_uuid at 0x7f28775d9e60>
[ERROR] TableError: Failed to create table: Parameter validation failed:
Unknown parameter in input: "BillingMode", must be one of: AttributeDefinitions, TableName, KeySchema, LocalSecondaryIndexes, GlobalSecondaryIndexes, ProvisionedThroughput, StreamSpecification, SSESpecification

Traceback (most recent call last):
  File "/var/task/handler.py", line 602, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 248, in lambda_handler
    return handler.handler(event, context)
  File "/var/task/handler.py", line 382, in handler
    result = self.run_function(app_function, event, context)
  File "/var/task/handler.py", line 283, in run_function
    result = app_function(event, context) if varargs else app_function()
  File "/var/task/create_tables.py", line 5, in create_post
    Post.create_table(billing_mode="PROVISIONED", read_capacity_units=1, write_capacity_units=1, wait=True)
  File "/var/task/pynamodb/models.py", line 732, in create_table
    **schema
  File "/var/task/pynamodb/connection/table.py", line 283, in create_table
    billing_mode=billing_mode
  File "/var/task/pynamodb/connection/base.py", line 631, in create_table
    raise TableError("Failed to create table: {}".format(e), e)
```

For further information, I'm using `pynamodb==4.0.0`, which installed `botocore==1.12.227` and `boto3==1.9.227`.

My `zappa_settings.json` is as follows:
```json
    "base": {
        "app_function": "example.app",
        "profile_name": "default",
        "project_name": "api",
        "runtime": "python3.7",
        "s3_bucket": "zappa-deployments-<edited>",
	"memory_size": 128,
	"keep_warm": false
    },
    "dev": {
	"extends": "base",
	"aws_region": "us-east-1",
	"aws_environment_variables": {
	    "env": "dev"
	}
    },
   ...
}
```

Thank you in advance for any hint or solution attempt.

**Comment by ikonst** [comment] 2019-09-13 14:19
Not sure why it happens. Supposedly we fixed it in https://github.com/pynamodb/PynamoDB/pull/648. Can you double check (with `pip show botocore`) what version you have?

**Comment by trenta3** [comment] 2019-09-13 14:36
Of course.

```bash
$ pip show botocore
Name: botocore
Version: 1.12.227
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /home/trenta3/Documenti/aws-website-tutorial/api/venv/lib/python3.7/site-packages
Requires: python-dateutil, urllib3, docutils, jmespath
Required-by: zappa, s3transfer, pynamodb, boto3
```

**Comment by Yaronn44** [comment] 2019-09-16 14:52
Same problem here with `pynamodb==4.0.0`, ` botocore 1.12.228` and `boto3==1.9.228`

**Comment by ikonst** [comment] 2019-09-16 17:23
For a sanity check, can you do
```
import botocore
print(botocore.__version__)
```
from the same code that exhibits the problem?

**Comment by michalkurpis** [comment] 2019-09-17 08:20
@trenta3 @Yaronn44 
The problem is caused by fact that `Zappa` do not copy your local version of `botocore` and `boto3` by default, so lambda function uses built-in version which is `1.12.42` for `botocore` and `1.9.42` for `boto3` (Python 3.7)
To fix that issue and add your local version of `botocore` and/or `boto3` add `exclude` setting to your `zappa_settings.json`:

```
{
    "dev": {
        "exclude": [
                "*.gz",
                "*.rar"
            ]
        }
}
```
[How zappa makes packages](https://github.com/Miserlou/Zappa/blob/master/README.md#how-zappa-makes-packages)

**Comment by ikonst** [comment] 2019-09-17 17:59
Assuming this is a zappa issue, so I'm closing. Reopen if you feel this is still a problem with PynamoDB.

We can consider adding a runtime check for the botocore version and emit a warning.

**Closed by ikonst** 2019-09-17 17:59 UTC
