### ISSUE TITLE
Bug with serializing/deserializing UTCDateTimeAttribute

### ISSUE THREAD

**Issue by FWirtz** [pynamodb/PynamoDB#364] opened 2017-10-02 16:09 UTC
Hello,

When saving a Model with a `UTCDateTimeAttribute` parameter, `serialize` and `deserialize` don't get called correctly.

Throws: `AttributeError: 'str' object has no attribute 'tzinfo'`

## Steps to reproduce
I have a model `MyModel` that has a couple parameters, one being a `UTCDateTimeAttribute`.
When retrieving an object of that model, changing the value of one (different) parameter, and then calling `save()`, the error gets thrown. 
```
my_object = MyModel.get(id)
kwargs = {
    **my_object.as_dict(),
    'changed_param': 'SOMETHING'
}

my_object_modified = MyModel(**kwargs)
my_object_modified.save()
```

## How to also throw the error
Creating a string and calling the `serialize` and `deserialize` functions manually, the same error occurs:
```
>>> s = '2017-09-28T16:57:10.230930+0000'

>>> UTCDateTimeAttribute().deserialize(s)
datetime.datetime(2017, 9, 28, 16, 57, 10, 230930, tzinfo=datetime.timezone.utc)

>>> UTCDateTimeAttribute().serialize(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "(...)/pynamodb/attributes.py", line 387, in serialize
    if value.tzinfo is None:
AttributeError: 'str' object has no attribute 'tzinfo'
```

The second behaviour is **expected**, just validating my point.
Also, when calling `serialize()` on the deserialized object, everything again works as exptected.

## Where the bug probably resides
I expect the bug to be in the save function of the model, don't know where though.

Can somebody confirm this?

See also #340, #162 

## Workaround
I worked around this issue by turning the `UTCDateTimeAttribute` into a `UnicodeAttribute`.

**Comment by jpinner-lyft** [comment] 2017-10-16 15:39
@FWirtz I'm not able to reproduce this issue using the latest version of pynamo (3.2.0).

The Model class does not have a `as_dict` function (the MapAttribute class does). Could you perhaps post the class definition of `MyModel`?

**Comment by davidroeca** [comment] 2017-10-18 22:57
@jpinner-lyft I'm experiencing the same issue, python 3.6, 3.2.0

```python
from datetime import datetime
from pynamodb.attributes import UnicodeAttribute, UTCDateTimeAttribute
class MyModel(Model):
    class Meta:
        table_name = 'my_model'
    name = UnicodeAttribute(hash_key=True)
    updated = UTCDateTimeAttribute(range_key=True, default=datetime.utcnow)

if not MyModel.exists():
    MyModel.create(wait=True)
new_model = MyModel(name='David')
new_model.save() # this is fine
MyModel.get('David') # AttributeError: 'str' object has no attribute 'tzinfo'
```

While I understand that I can install another third party module to handle this (pytz), I think it would be nice to support python's builtin datetime methods

**Comment by jpinner-lyft** [comment] 2017-10-18 23:05
@davidroeca in your example you can't run `MyModel.get('David')` since your model has a range key. That being said, I've updated your example and get the following (python 3.6, 3.2.0):

```
>>> from datetime import datetime
>>> from pynamodb.attributes import UnicodeAttribute, UTCDateTimeAttribute
>>> from pynamodb.models import Model
>>> 
>>> class MyModel(Model):
...     class Meta:
...         table_name = 'my_model'
...         host = 'http://localhost:8000'
...     name = UnicodeAttribute(hash_key=True)
...     updated = UTCDateTimeAttribute(range_key=True, default=datetime.utcnow)
... 
>>> MyModel.create_table(wait=True, read_capacity_units=1, write_capacity_units=1)
>>> new_model = MyModel(name='David')
>>> new_model.save()
{}
>>> david = list(MyModel.query('David'))[0]
>>> david.updated
datetime.datetime(2017, 10, 18, 23, 2, 2, 897250, tzinfo=tzutc())
```

So as you can see, I'm still having trouble reproducing the issue.

**Comment by davidroeca** [comment] 2017-10-18 23:09
@jpinner-lyft ah yes that resolved it--new user to both this library and dynamodb, sorry for the confusion

**Comment by jpinner-lyft** [comment] 2017-10-18 23:12
@davidroeca No worries! I think I'm going to close the issue as "Can't Reproduce" and let @FWirtz re-open with a reproducible example on 3.2.0+.

**Closed** 2017-10-18 23:14 UTC

**Comment by mastercoder8** [comment] 2021-02-01 23:36
Just use 
```
            if isinstance(attr, UTCDateTimeAttribute):
                yield name, getattr(self, name)
```
